source 'https://rubygems.org'
# ruby '2.1.2'
gem 'sinatra'
gem 'unicorn'
gem 'net-ssh'
gem 'highline', '~> 1.7', '>= 1.7.8'
gem 'capistrano', '2.15.4'
gem 'capistrano-ext'
gem 'capistrano-rbenv', '1.0.5'
