"develop":
  - role: 'staging'
    name: 'beta machine'
    node_ip: '52.31.107.xx'
    notify: 'pradeep.achuthan@zipgo.in'
    deploy_path: "/home/ubuntu/deploy_config/deploy.staging.rb"
    config_path: "/home/ubuntu/deploy_config/staging.rb"
  - role: 'staging'
    name: 'staging machine'
    node_ip: '52.31.107.11'
    notify: 'pradeep.achuthan@zipgo.in'
    deploy_path: "/home/ubuntu/deploy_config/deploy.staging.rb"
    config_path: "/home/ubuntu/deploy_config/staging.rb"
"master":
  - role: 'production'
    name: 'beta machine'
    node_ip: '52.30.61.166'
    notify: 'pradeep.achuthan@zipgo.in'
    deploy_path: "/home/ubuntu/deploy_config/deploy.production.rb"
    config_path: "/home/ubuntu/deploy_config/production.rb"
  - role: 'production'
    name: 'production machine'
    node_ip: '52.31.107.xx'
    notify: 'pradeep.achuthan@zipgo.in'
    deploy_path: "/home/ubuntu/deploy_config/deploy.staging.rb"
    config_path: "/home/ubuntu/deploy_config/production.rb"
